const express = require('express');
const router = express.Router();
const authenticate = require('../middleware/auth');
const { requireRole } = require('../middleware/role');
const Batch = require('../models/Batch');
const BatchChange = require('../models/BatchChange');
const Notification = require('../models/Notification');

// @route   POST /api/batches
// @desc    Create a new batch
// @access  Private (Farmer only)
router.post('/', authenticate, requireRole('farmer'), async (req, res) => {
  try {
    const {
      herbName,
      harvestDate,
      quantityKg,
      farmingConditions,
      moistureLevel,
      pricePerKg,
      purityReportUrl,
      images
    } = req.body;

    // Validation
    if (!herbName || !harvestDate || !quantityKg) {
      return res.status(400).json({
        success: false,
        message: 'Please provide herb name, harvest date, and quantity'
      });
    }

    // Create batch
    const batch = new Batch({
      batchNumber: '', // Will be auto-generated by pre-save hook
      farmerId: req.user.id,
      herbName,
      harvestDate: new Date(harvestDate),
      quantityKg: parseFloat(quantityKg),
      farmingConditions,
      moistureLevel: moistureLevel ? parseFloat(moistureLevel) : undefined,
      pricePerKg: pricePerKg ? parseFloat(pricePerKg) : undefined,
      purityReportUrl,
      images: images || [],
      status: 'pending_approval'
    });

    await batch.save();

    // Create notification for admin
    await Notification.create({
      userId: req.user.id, // This will be replaced by admin notification logic
      title: 'New Batch Created',
      message: `New batch ${batch.batchNumber} (${herbName}) is pending approval`,
      type: 'batch_created',
      relatedId: batch._id,
      relatedModel: 'Batch'
    });

    res.status(201).json({
      success: true,
      data: batch
    });
  } catch (error) {
    console.error('Create batch error:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating batch',
      error: error.message
    });
  }
});

// @route   GET /api/batches
// @desc    Get all batches (with filters)
// @access  Private
router.get('/', authenticate, async (req, res) => {
  try {
    const { status, herbName, farmerId, page = 1, limit = 20, search } = req.query;
    
    const query = {};

    // Apply filters
    if (status) {
      query.status = status;
    }

    if (herbName) {
      query.herbName = { $regex: herbName, $options: 'i' };
    }

    if (farmerId) {
      query.farmerId = farmerId;
    }

    if (search) {
      query.$or = [
        { herbName: { $regex: search, $options: 'i' } },
        { batchNumber: { $regex: search, $options: 'i' } }
      ];
    }

    // Different query based on user role
    if (req.user.role === 'farmer') {
      query.farmerId = req.user.id;
    } else if (req.user.role === 'company') {
      // Companies can see batches in various statuses
      query.status = { $in: ['pending_approval', 'approved', 'in_process', 'quality_check', 'packaging', 'ready_for_sale', 'shipped', 'unavailable'] };
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const batches = await Batch.find(query)
      .populate('farmerId', 'fullName phone')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit));

    const total = await Batch.countDocuments(query);

    res.json({
      success: true,
      data: batches,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / parseInt(limit))
      }
    });
  } catch (error) {
    console.error('Get batches error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching batches',
      error: error.message
    });
  }
});

// @route   GET /api/batches/:id
// @desc    Get single batch by ID
// @access  Private
router.get('/:id', authenticate, async (req, res) => {
  try {
    const batch = await Batch.findById(req.params.id)
      .populate('farmerId', 'fullName phone email');

    if (!batch) {
      return res.status(404).json({
        success: false,
        message: 'Batch not found'
      });
    }

    res.json({
      success: true,
      data: batch
    });
  } catch (error) {
    console.error('Get batch error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching batch',
      error: error.message
    });
  }
});

// @route   GET /api/batches/batch-number/:batchNumber
// @desc    Get batch by batch number (for QR verification)
// @access  Public
router.get('/batch-number/:batchNumber', async (req, res) => {
  try {
    const batch = await Batch.findOne({ batchNumber: req.params.batchNumber })
      .populate('farmerId', 'fullName phone');

    if (!batch) {
      return res.status(404).json({
        success: false,
        message: 'Batch not found'
      });
    }

    // Get status timeline
    const timeline = await BatchChange.find({ batchId: batch._id })
      .sort({ changedAt: 1 });

    res.json({
      success: true,
      data: {
        ...batch.toJSON(),
        timeline
      }
    });
  } catch (error) {
    console.error('Get batch by number error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching batch',
      error: error.message
    });
  }
});

// @route   PUT /api/batches/:id
// @desc    Update batch
// @access  Private (Farmer only, owner of batch)
router.put('/:id', authenticate, requireRole('farmer'), async (req, res) => {
  try {
    const batch = await Batch.findById(req.params.id);

    if (!batch) {
      return res.status(404).json({
        success: false,
        message: 'Batch not found'
      });
    }

    // Check ownership
    if (batch.farmerId.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to update this batch'
      });
    }

    // Only allow updates if batch is pending_approval
    if (batch.status !== 'pending_approval') {
      return res.status(400).json({
        success: false,
        message: 'Cannot update batch after approval process has started'
      });
    }

    const allowedUpdates = [
      'herbName', 'harvestDate', 'quantityKg', 'farmingConditions',
      'moistureLevel', 'pricePerKg', 'purityReportUrl', 'images'
    ];

    const updates = {};
    allowedUpdates.forEach(field => {
      if (req.body[field] !== undefined) {
        updates[field] = req.body[field];
      }
    });

    Object.assign(batch, updates);
    await batch.save();

    res.json({
      success: true,
      data: batch
    });
  } catch (error) {
    console.error('Update batch error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating batch',
      error: error.message
    });
  }
});

// @route   PATCH /api/batches/:id/status
// @desc    Update batch status
// @access  Private (Admin, Farmer for specific transitions)
router.patch('/:id/status', authenticate, async (req, res) => {
  try {
    const { status } = req.body;

    if (!status) {
      return res.status(400).json({
        success: false,
        message: 'Status is required'
      });
    }

    const batch = await Batch.findById(req.params.id);

    if (!batch) {
      return res.status(404).json({
        success: false,
        message: 'Batch not found'
      });
    }

    const oldStatus = batch.status;

    // Record status change
    await BatchChange.create({
      batchId: batch._id,
      fieldName: 'status',
      oldValue: oldStatus,
      newValue: status,
      changedBy: req.user.id
    });

    batch.status = status;
    
    // Handle sold/unavailable status
    if (status === 'sold' || status === 'unavailable') {
      batch.availableQuantityKg = 0;
    }

    await batch.save();

    // Notify farmer of status change
    await Notification.create({
      userId: batch.farmerId,
      title: 'Batch Status Updated',
      message: `Your batch ${batch.batchNumber} status changed to ${status}`,
      type: 'batch_status_changed',
      relatedId: batch._id,
      relatedModel: 'Batch'
    });

    res.json({
      success: true,
      data: batch
    });
  } catch (error) {
    console.error('Update status error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating status',
      error: error.message
    });
  }
});

// @route   DELETE /api/batches/:id
// @desc    Delete batch
// @access  Private (Farmer only, owner of batch)
router.delete('/:id', authenticate, requireRole('farmer'), async (req, res) => {
  try {
    const batch = await Batch.findById(req.params.id);

    if (!batch) {
      return res.status(404).json({
        success: false,
        message: 'Batch not found'
      });
    }

    // Check ownership
    if (batch.farmerId.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to delete this batch'
      });
    }

    // Only allow deletion if batch is pending_approval
    if (batch.status !== 'pending_approval') {
      return res.status(400).json({
        success: false,
        message: 'Cannot delete batch after approval process has started'
      });
    }

    await Batch.findByIdAndDelete(req.params.id);

    res.json({
      success: true,
      message: 'Batch deleted successfully'
    });
  } catch (error) {
    console.error('Delete batch error:', error);
    res.status(500).json({
      success: false,
      message: 'Error deleting batch',
      error: error.message
    });
  }
});

// @route   GET /api/batches/:id/timeline
// @desc    Get batch status timeline
// @access  Private
router.get('/:id/timeline', authenticate, async (req, res) => {
  try {
    const timeline = await BatchChange.find({ batchId: req.params.id })
      .populate('changedBy', 'fullName')
      .sort({ changedAt: 1 });

    res.json({
      success: true,
      data: timeline
    });
  } catch (error) {
    console.error('Get timeline error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching timeline',
      error: error.message
    });
  }
});

module.exports = router;

